# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado_Projects/practice/project_1_16/project_1_16.cache/wt [current_project]
set_property parent.project_path D:/Vivado_Projects/practice/project_1_16/project_1_16.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/new/camera_interface.sv
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/new/filter.sv
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/new/reg_mem.sv
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/new/top_module.sv
}
read_verilog -library xil_defaultlib {
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/asyn_fifo.v
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/clock_divisor.v
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/debounce_explicit.v
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/i2c_top.v
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/mem_addr_gen.v
  D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/imports/src/vga.v
}
read_ip -quiet D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_12MHz/dcm_12MHz.xci
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_12MHz/dcm_12MHz_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_12MHz/dcm_12MHz.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_12MHz/dcm_12MHz_late.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_12MHz/dcm_12MHz_ooc.xdc]

read_ip -quiet D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xci
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_late.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_ooc.xdc]

read_ip -quiet D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_165MHz/dcm_165MHz.xci
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_165MHz/dcm_165MHz_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_165MHz/dcm_165MHz.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_165MHz/dcm_165MHz_late.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/sources_1/ip/dcm_165MHz/dcm_165MHz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/constrs_1/imports/src/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Vivado_Projects/practice/project_1_16/project_1_16.srcs/constrs_1/imports/src/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
