# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xci
# IP: The module: 'dcm_24MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xci
# IP: The module: 'dcm_24MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Projects/I2c/project_7/project_7.srcs/sources_1/ip/dcm_24MHz/dcm_24MHz_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
